"""empty message

Revision ID: 26bfc45b8905
Revises: a34c64d38d29
Create Date: 2019-12-21 12:45:47.437769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bfc45b8905'
down_revision = 'a34c64d38d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('compositeur', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'compositeur')
    # ### end Alembic commands ###
