"""empty message

Revision ID: 4745e8ded1dc
Revises: 885dabda8af4
Create Date: 2019-12-22 12:09:39.923226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4745e8ded1dc'
down_revision = '885dabda8af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    op.add_column('partition', sa.Column('nbr_download', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partition', 'nbr_download')
    op.create_table('download',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nbr_download', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('partition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('statut', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partition_id'], ['partition.id'], name='download_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='download_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
