"""empty message

Revision ID: 885dabda8af4
Revises: 26bfc45b8905
Create Date: 2019-12-21 14:31:17.582199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885dabda8af4'
down_revision = '26bfc45b8905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('imagesurl', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'imagesurl')
    # ### end Alembic commands ###
