"""empty message

Revision ID: a34c64d38d29
Revises: 
Create Date: 2019-12-21 12:35:33.479322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34c64d38d29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=True),
    sa.Column('post_nom', sa.String(length=128), nullable=True),
    sa.Column('prenom', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=128), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.Column('document_pdf', sa.String(length=200), nullable=True),
    sa.Column('date_pub', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre_parti', sa.String(length=128), nullable=True),
    sa.Column('pdf_url', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nbr_download', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['partition_id'], ['partition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    op.drop_table('partition')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('types')
    op.drop_table('categorie')
    # ### end Alembic commands ###
