"""empty message

Revision ID: d7ab7b69d88a
Revises: cfc35658049a
Create Date: 2019-12-28 11:47:32.461786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ab7b69d88a'
down_revision = 'cfc35658049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('nbr_lecture', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'nbr_lecture')
    # ### end Alembic commands ###
